// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdMIxFSYA5P75KR7RZkC3lDsOMzLRKbbg',
    appId: '1:272363630855:android:1d400fba4029c9efd915a2',
    messagingSenderId: '272363630855',
    projectId: 'oh-app-bcf24',
    storageBucket: 'oh-app-bcf24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIdUSOSICJxy8UTj-RI8ehTFx1v2IW6M8',
    appId: '1:272363630855:ios:56d177d8f1138867d915a2',
    messagingSenderId: '272363630855',
    projectId: 'oh-app-bcf24',
    storageBucket: 'oh-app-bcf24.appspot.com',
    androidClientId: '272363630855-2k4iq3kls4hrlq0pocdqp3tho7fm527t.apps.googleusercontent.com',
    iosClientId: '272363630855-4pu4p3e2i9lke1ua0hggt3u1tif20k1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.clickOoh',
  );
}
